# For physics topics, use the specific subtopics, e.g. "Astrophysics"
topic: ["Computer Science", Quantatative Finance"]
# An empty list here will include all categories in a topic
# Use the natural language names of the topics, found here: https://arxiv.org
# Including more categories will result in more calls to the large language model
categories: []

# Relevance score threshold. abstracts that receive a score less than this from the large language model
# will have their papers filtered out.
#
# Must be within 1-10
threshold: 7

# A natural language statement that the large language model will use to judge which papers are relevant 
#
# For example:
#     "I am interested in complexity theory papers that establish upper bounds"
#     "gas chromatography, mass spectrometry"
#     "making lots of money"
#
# This can be empty, which just return a full list of papers with no judgement or filtering,
# in whatever order arXiv responds with.
interest: |
  1. Machine learning and neural network models for electricity price forecasting specifically related to electricity price spikes.
  2. Graph neural networks or spatio-temporal models for predicitng locational marginal prices (LMPs).
  3. meta-learning models to perform weighted aggregate prediction from multiple models.
  4. Mostly interested in papers from 2017 and newer however relevant papers from older sources may be useful if they have high citation.
